### PR TITLE
add bower staffs and two new positions 'fluid-top' and 'fluid-bottom'

### PR DESCRIPTION
**Pull request by aispin**
1. Add bower staffs
2. Two new positions 'fluid-top' and 'fluid-bottom'

### CODE REVIEW

**Comment by 4ndv** [comment]
Yes, but can you unregister it from bower registry?

**Comment by 4ndv** [comment]
@mamboer hello?

**Comment by 4ndv** [comment]
@mamboer, please, remove package from bower registry, so i can update it in future.

**Comment by aispin** [comment]
@andreyviktorov 
Hey, i'v removed it from bower and use my github version instead in my project.
Sorry for long time without responses, i'm quite busy~
BTW , i suggest you register it as soon as possible. :)

**Comment by aispin** [comment]
Will u merge my PR?

**Comment by 4ndv** [comment]
Thank you :)
I will merge it once my electricity back

**Comment by 4ndv** [comment]
I'm from phone now..

**Comment by 4ndv** [comment]
Thank you, merged into `dev`! :)

**Pull request closed without merging**
